CREATE TABLE IF NOT EXISTS sms_billing_accounts (
 company_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
 rate_mills INT UNSIGNED NOT NULL DEFAULT 50,
 unlimited TINYINT UNSIGNED NOT NULL DEFAULT 0,
 FOREIGN KEY (company_id) REFERENCES companies(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS sms_charges (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 company_id BIGINT UNSIGNED NOT NULL,
 request_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 payload_hash CHAR(64) CHARACTER SET ascii NOT NULL,
 payload TEXT NOT NULL,
 remote_id BIGINT UNSIGNED NULL,
 rate_mills INT UNSIGNED NOT NULL,
 segments INT UNSIGNED NOT NULL,
 recipients INT UNSIGNED NOT NULL,
 reserved_cents BIGINT UNSIGNED NOT NULL,
 charged_cents BIGINT UNSIGNED NULL,
 status ENUM('reserved','running','settled','rejected') NOT NULL DEFAULT 'reserved',
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_sms_request(company_id,request_id),
 KEY idx_sms_status(status,id),
 FOREIGN KEY (company_id) REFERENCES companies(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS admin_events (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 action VARCHAR(64) NOT NULL,
 details TEXT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
